### PR TITLE
Design

### PR DESCRIPTION
**Pull request by balapa**

### CODE REVIEW

**Comment by ChristopherGS** [comment]
```
MacBook-Pro:christophergs.github.io christophersamiullah$ jekyll serve
/Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'github-pages' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
```
@balapa 
Fixed by installing the gem - but does this need to be captured anywhere in the project requirements? (I'm thinking about the deployment)

**Comment by ChristopherGS** [comment]
Feedback:

- Add .gif to portfolio of property scouting from this page: https://www.propertyscouting.co.uk/property-type-insights/

- ChrisGS should be ChristopherGS

- remove fb and twitter from blog

- Home page nav bar does not align with page nav bars (i.e. home vs. CV)

- blog text on mobile should be *slightly* larger

- hook up indie hacker and github urls (https://www.indiehackers.com/ChristopherGS)

- On mobile tags look a bit disordered at the bottom of blog posts

- Can we add a very subtle effect to the home page on load - just to make it pop a little bit.

**Comment by ChristopherGS** [comment]
Finally, we need to hookup the mailchimp form - what do you need for this?

**Comment by ChristopherGS** [comment]
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://protonmail.us20.list-manage.com/subscribe/post?u=ea649ac4a565cee1d0b09f395&amp;id=6c46d8e69c" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>Subscribe For Content Updates (No Spam)</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_ea649ac4a565cee1d0b09f395_6c46d8e69c" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

**Comment by balapa** [comment]
> ```
> MacBook-Pro:christophergs.github.io christophersamiullah$ jekyll serve
> /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/resolver.rb:287:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'github-pages' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
> ```
> 
> @balapa
> Fixed by installing the gem - but does this need to be captured anywhere in the project requirements? (I'm thinking about the deployment)

This error was caused by the Gemfile file. You don't really need Gemfile to host the site on GitHub Pages but I need it to host the demo on netlify. Once we're done with the feedback, you can remove the Gemfile.

**Comment by balapa** [comment]
> * Add .gif to portfolio of property scouting from this page: https://www.propertyscouting.co.uk/property-type-insights/

I don't see any gif file on that page

**Comment by balapa** [comment]
I've updated the website based on your feedback and also added the mailchimp form.

**Pull request merged**
